<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\Application;
use MultiFlexi\Conffield;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:43.
 */
class ApplicationTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Application();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Application::getCompany
     */
    public function testgetCompany(): void
    {
        $this->assertEquals('', $this->object->getCompany());
    }

    /**
     * @covers \MultiFlexi\Application::takeData
     */
    public function testtakeData(): void
    {
        $this->assertEquals(3, $this->object->takeData(['enabled' => 'on', 'executable' => '/bin/test']));
    }

    /**
     * @covers \MultiFlexi\Application::findBinaryInPath
     */
    public function testfindBinaryInPath(): void
    {
        $this->assertEquals('/usr/bin/bash', $this->object->findBinaryInPath('bash'));
    }

    /**
     * @covers \MultiFlexi\Application::doesBinaryExist
     */
    public function testdoesBinaryExist(): void
    {
        $this->assertTrue($this->object->doesBinaryExist('/usr/bin/tar'));
    }

    /**
     * @covers \MultiFlexi\Application::isBinaryInPath
     */
    public function testisBinaryInPath(): void
    {
        $this->assertTrue($this->object->isBinaryInPath('more'));
    }

    /**
     * @covers \MultiFlexi\Application::getPlatformApps
     */
    public function testgetPlatformApps(): void
    {
        $this->assertEquals([], $this->object->getPlatformApps('Unix'));
    }

    /**
     * @covers \MultiFlexi\Application::getAppJson
     */
    public function testgetAppJson(): void
    {
        $this->assertEquals(<<<'EOD'
{
    "environment": [],
    "multiflexi": "dev-main"
}
EOD, $this->object->getAppJson());
    }

    /**
     * @covers \MultiFlexi\Application::jsonFileName
     */
    public function testjsonFileName(): void
    {
        $this->assertEquals('.multiflexi.app.json', $this->object->jsonFileName());
    }

    public function testimportAppJson(): void
    {
        $this->object->importAppJson(__DIR__.'/../../test.multiflexi.app.json');
        $this->assertEquals('775ed801-2489-4981-bc14-d8a01cba1938', $this->object->getDataValue('uuid'));
    }

    /**
     * @covers \MultiFlexi\Application::getResultFiles
     */
    public function testGetResultFilesReturnsArray(): void
    {
        $result = $this->object->getResultFiles();
        $this->assertIsArray($result);
    }

    /**
     * @covers \MultiFlexi\Application::getResultFiles
     */
    public function testGetResultFilesEmptyForNewApplication(): void
    {
        $app = new Application();
        $result = $app->getResultFiles();
        $this->assertIsArray($result);
        $this->assertEmpty($result);
    }

    /**
     * @covers \MultiFlexi\Application::getResultFiles
     */
    public function testGetResultFilesFindsMatchingFiles(): void
    {
        // Create a temp file that would match a pattern
        $tmpDir = sys_get_temp_dir();
        $tmpFile = tempnam($tmpDir, 'mftest_');
        $jsonFile = $tmpFile.'.json';
        rename($tmpFile, $jsonFile);
        file_put_contents($jsonFile, '{"test": true}');

        try {
            // Without app_artifacts in DB, getResultFiles should still return array
            $result = $this->object->getResultFiles();
            $this->assertIsArray($result);
        } finally {
            // Clean up
            if (file_exists($jsonFile)) {
                unlink($jsonFile);
            }
        }
    }

    /**
     * @covers \MultiFlexi\Application::getProduces
     */
    public function testGetProducesReturnsArrayForNewApp(): void
    {
        // A fresh Application with no key returns an empty array (no DB query).
        $app = new \MultiFlexi\Application();
        $result = $app->getProduces();
        $this->assertIsArray($result);
        $this->assertEmpty($result, 'getProduces() must return [] when app has no ID');
    }

    /**
     * @covers \MultiFlexi\Application::getConsumes
     */
    public function testGetConsumesReturnsArrayForNewApp(): void
    {
        $app = new \MultiFlexi\Application();
        $result = $app->getConsumes();
        $this->assertIsArray($result);
        $this->assertEmpty($result, 'getConsumes() must return [] when app has no ID');
    }

    /**
     * @covers \MultiFlexi\Application::importProduces
     * @covers \MultiFlexi\Application::importConsumes
     */
    public function testImportProducesAndConsumesRequireDB(): void
    {
        // importProduces / importConsumes are protected and require a live DB.
        // We verify they exist via reflection and are callable from a subclass context.
        $ref = new \ReflectionClass(\MultiFlexi\Application::class);

        $this->assertTrue(
            $ref->hasMethod('importProduces'),
            'Application must declare importProduces()',
        );
        $this->assertTrue(
            $ref->hasMethod('importConsumes'),
            'Application must declare importConsumes()',
        );

        $importProduces = $ref->getMethod('importProduces');
        $importConsumes = $ref->getMethod('importConsumes');

        $this->assertTrue($importProduces->isProtected());
        $this->assertTrue($importConsumes->isProtected());
    }

    /**
     * @covers \MultiFlexi\Application::checkRequiredFields
     */
    public function testCheckRequiredFieldsValidatesSubmittedDataNotStoredState(): void
    {
        $pdo = new \PDO(
            'mysql:host='.\Ease\Shared::cfg('DB_HOST').';port='.\Ease\Shared::cfg('DB_PORT').';dbname='.\Ease\Shared::cfg('DB_DATABASE'),
            \Ease\Shared::cfg('DB_USERNAME'),
            \Ease\Shared::cfg('DB_PASSWORD'),
        );
        $appId = (int) $pdo->query('SELECT id FROM apps ORDER BY id LIMIT 1')->fetchColumn();
        $fieldName = 'PHPUNIT_REQUIRED_FIELD_TEST';

        (new Conffield())->insertToSQL([
            'app_id' => $appId,
            'keyname' => $fieldName,
            'type' => 'string',
            'description' => 'PHPUnit required-field test',
            'required' => 1,
        ]);

        try {
            $app = new Application($appId);

            // Submitted data is missing the required key -> must fail, even
            // though a stored default might otherwise satisfy it.
            $this->assertFalse($app->checkRequiredFields(['OTHER_FIELD' => 'x']));

            // Submitted data provides the required key -> must pass.
            $this->assertTrue($app->checkRequiredFields([$fieldName => 'some value']));

            // Submitted data provides the required key but empty -> must fail.
            $this->assertFalse($app->checkRequiredFields([$fieldName => '']));
        } finally {
            (new Conffield())->deleteFromSQL(['app_id' => $appId, 'keyname' => $fieldName]);
        }
    }

    /**
     * @covers \MultiFlexi\Application::getAppJson
     */
    public function testGetAppJsonDoesNotIncludeProducesConsumesForNewApp(): void
    {
        // A new Application (no ID, no DB) should export only environment and multiflexi.
        $json = $this->object->getAppJson();
        $decoded = json_decode($json, true);

        $this->assertIsArray($decoded);
        // produces and consumes are only injected when the app has an ID.
        $this->assertArrayNotHasKey('produces', $decoded);
        $this->assertArrayNotHasKey('consumes', $decoded);
    }
}
