<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\Conffield;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:33.
 */
class ConffieldTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Conffield();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Conffield::takeData
     */
    public function testTakeDataPreservesBoolFlagsLoadedFromSql(): void
    {
        // Simulates what loadFromSQL() passes in: a raw DB row where
        // required/secret/multiline/expiring are already 0/1, not the
        // HTML-checkbox literal 'on'. A prior bug forced these back to 0
        // on every load because the coercion only recognized 'on'.
        $this->object->takeData([
            'app_id' => 1,
            'keyname' => 'TEST',
            'type' => 'bool',
            'required' => 1,
            'secret' => 0,
            'multiline' => 1,
            'expiring' => 0,
        ]);

        $this->assertSame(1, $this->object->getDataValue('required'));
        $this->assertSame(0, $this->object->getDataValue('secret'));
        $this->assertSame(1, $this->object->getDataValue('multiline'));
        $this->assertSame(0, $this->object->getDataValue('expiring'));
    }

    /**
     * @covers \MultiFlexi\Conffield::takeData
     */
    public function testTakeDataCoercesHtmlCheckboxSubmission(): void
    {
        // Checked HTML checkboxes submit the literal string 'on'; unchecked
        // ones are simply absent from $_POST.
        $this->object->takeData([
            'app_id' => 1,
            'keyname' => 'TEST',
            'type' => 'bool',
            'required' => 'on',
            // 'secret' intentionally absent => unchecked
        ]);

        $this->assertSame(1, $this->object->getDataValue('required'));
        $this->assertSame(0, $this->object->getDataValue('secret'));
    }

    /**
     * @covers \MultiFlexi\Conffield::appConfigs
     *
     * @todo   Implement testappConfigs().
     */
    public function testappConfigs(): void
    {
        $this->assertEquals('', $this->object->appConfigs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Conffield::getAppConfigs
     *
     * @todo   Implement testgetAppConfigs().
     */
    public function testgetAppConfigs(): void
    {
        $this->assertEquals('', $this->object->getAppConfigs(new \MultiFlexi\Application()));
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
