<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\Conffield;
use MultiFlexi\Configuration;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:33.
 */
class ConfigurationTest extends \PHPUnit\Framework\TestCase
{
    protected $object;
    private static ?int $testAppId = null;
    private static string $boolFieldName = 'PHPUNIT_BOOL_COERCION_TEST';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Configuration();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    private static function testAppId(): int
    {
        if (self::$testAppId === null) {
            $pdo = new \PDO(
                'mysql:host='.\Ease\Shared::cfg('DB_HOST').';port='.\Ease\Shared::cfg('DB_PORT').';dbname='.\Ease\Shared::cfg('DB_DATABASE'),
                \Ease\Shared::cfg('DB_USERNAME'),
                \Ease\Shared::cfg('DB_PASSWORD'),
            );
            $id = $pdo->query('SELECT id FROM apps ORDER BY id LIMIT 1')->fetchColumn();
            self::$testAppId = (int) $id;
        }

        return self::$testAppId;
    }

    /**
     * A 'bool' typed conffield row must exist for the coercion loop in
     * Configuration::takeData() to find and act on it.
     */
    private function seedBoolConffield(): void
    {
        // Not using Conffield::addAppConfig() here: it writes a 'name' column
        // that doesn't exist on the 'conffield' table (a separate, pre-existing
        // bug found during investigation) and would fatal on insert.
        (new Conffield())->insertToSQL([
            'app_id' => self::testAppId(),
            'keyname' => self::$boolFieldName,
            'type' => 'bool',
            'description' => 'PHPUnit coercion test field',
        ]);
    }

    private function removeBoolConffield(): void
    {
        (new Conffield())->deleteFromSQL(['app_id' => self::testAppId(), 'keyname' => self::$boolFieldName]);
    }

    /**
     * @covers \MultiFlexi\Configuration::getName
     *
     * @todo   Implement testgetName().
     */
    public function testgetName(): void
    {
        $this->assertEquals('', $this->object->getName());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Configuration::saveToSQL
     *
     * @todo   Implement testsaveToSQL().
     */
    public function testsaveToSQL(): void
    {
        $this->assertEquals('', $this->object->saveToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Configuration::takeData
     */
    public function testTakeDataCoercesAbsentBoolFieldToFalse(): void
    {
        $this->seedBoolConffield();

        try {
            $this->object->setDataValue('app_id', self::testAppId());
            $this->object->takeData([]);

            $this->assertSame('false', $this->object->getDataValue(self::$boolFieldName));
        } finally {
            $this->removeBoolConffield();
        }
    }

    /**
     * @covers \MultiFlexi\Configuration::takeData
     */
    public function testTakeDataCoercesPresentBoolFieldToTrue(): void
    {
        $this->seedBoolConffield();

        try {
            $configuration = new Configuration();
            $configuration->setDataValue('app_id', self::testAppId());
            $configuration->takeData([self::$boolFieldName => 'true']);

            $this->assertSame('true', $configuration->getDataValue(self::$boolFieldName));
        } finally {
            $this->removeBoolConffield();
        }
    }

    /**
     * @covers \MultiFlexi\Configuration::setEnvironment
     *
     * @todo   Implement testsetEnvironment().
     */
    public function testsetEnvironment(): void
    {
        $this->assertEquals('', $this->object->setEnvironment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Configuration::getAppConfig
     *
     * @todo   Implement testgetAppConfig().
     */
    public function testgetAppConfig(): void
    {
        $this->assertEquals('', $this->object->getAppConfig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
