<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package.
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\Scheduler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:33.
 */
class SchedulerTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Scheduler();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Scheduler::__construct
     */
    public function testConstructSetsTable(): void
    {
        $scheduler = new Scheduler();
        $this->assertEquals('schedule', $scheduler->myTable);
    }

    /**
     * @covers \MultiFlexi\Scheduler::getIntervalEmoji
     */
    public function testGetIntervalEmoji(): void
    {
        $this->assertEquals('🎆', Scheduler::getIntervalEmoji('y'));
        $this->assertEquals('🔴', Scheduler::getIntervalEmoji('n'));
        $this->assertEquals('', Scheduler::getIntervalEmoji('unknown'));
    }

    /**
     * @covers \MultiFlexi\Scheduler::codeToInterval
     */
    public function testCodeToInterval(): void
    {
        $this->assertEquals('yearly', Scheduler::codeToInterval('y'));
        $this->assertEquals('monthly', Scheduler::codeToInterval('m'));
        $this->assertEquals('weekly', Scheduler::codeToInterval('w'));
        $this->assertEquals('daily', Scheduler::codeToInterval('d'));
        $this->assertEquals('hourly', Scheduler::codeToInterval('h'));
        $this->assertEquals('minutly', Scheduler::codeToInterval('i'));
        $this->assertEquals('disabled', Scheduler::codeToInterval('n'));
        $this->assertEquals('custom', Scheduler::codeToInterval('c'));
        $this->assertEquals('n/a', Scheduler::codeToInterval('bad'));
        $this->assertEquals('n/a', Scheduler::codeToInterval(null));
    }

    /**
     * @covers \MultiFlexi\Scheduler::codeToSeconds
     */
    public function testCodeToSeconds(): void
    {
        $this->assertEquals(31556926, Scheduler::codeToSeconds('y'));
        $this->assertEquals(2629743, Scheduler::codeToSeconds('m'));
        $this->assertEquals(604800, Scheduler::codeToSeconds('w'));
        $this->assertEquals(86400, Scheduler::codeToSeconds('d'));
        $this->assertEquals(3600, Scheduler::codeToSeconds('h'));
        $this->assertEquals(60, Scheduler::codeToSeconds('i'));
        $this->assertEquals(0, Scheduler::codeToSeconds('n'));
        $this->assertEquals(0, Scheduler::codeToSeconds('c'));
        $this->assertEquals(0, Scheduler::codeToSeconds('bad'));
        $this->assertEquals(0, Scheduler::codeToSeconds(null));
    }

    /**
     * @covers \MultiFlexi\Scheduler::intervalToCode
     */
    public function testIntervalToCode(): void
    {
        $this->assertEquals('y', Scheduler::intervalToCode('yearly'));
        $this->assertEquals('n/a', Scheduler::intervalToCode('bad'));
    }

    /**
     * @covers \MultiFlexi\Scheduler::getCurrentJobs
     */
    public function testGetCurrentJobsThrowsOnUnsupportedDb(): void
    {
        $scheduler = $this->getMockBuilder(Scheduler::class)
            ->onlyMethods(['getPdo'])
            ->getMock();
        $pdo = $this->createMock(\PDO::class);
        $pdo->method('getAttribute')->willReturn('unknown');
        $scheduler->method('getPdo')->willReturn($pdo);
        $this->expectException(\Exception::class);
        $scheduler->getCurrentJobs();
    }
}
