<?php
/**
 * Debian autoloader for php-vitexsoftware-multiflexi-core
 * Generated by phpab during package build
 */

// Load dependency autoloaders
require_once '/usr/share/php/EaseFluentPDO/autoload.php';
require_once '/usr/share/php/JsonSchema/autoload.php';
require_once '/usr/share/php/Symfony/Component/Process/autoload.php';
require_once '/usr/share/php/Cron/autoload.php';

// PSR-4 autoloader for MultiFlexi classes
spl_autoload_register(function (string $class): void {
    $here = __DIR__;

    $prefixes = [
      "MultiFlexi\\" => $here . "/",
    ];
    foreach ($prefixes as $prefix => $baseDir) {
        $len = strlen($prefix);
        if (strncmp($prefix, $class, $len) !== 0) {
            continue;
        }
        $relativeClass = substr($class, $len);
        $file = $baseDir . str_replace('\\', '/', $relativeClass) . '.php';
        if (file_exists($file)) {
            require $file;
            return;
        }
    }
});

// Load classes from plugin-capable directories explicitly.
$pluginDirectories = [
    '/usr/share/php/MultiFlexi/Action',
    '/usr/share/php/MultiFlexi/Env',
    '/usr/share/php/MultiFlexi/Executor',
    '/usr/share/php/MultiFlexi/Reporting',
    '/usr/share/php/MultiFlexi/CredentialProtoType',
];

foreach ($pluginDirectories as $pluginDirectory) {
    if (!is_dir($pluginDirectory)) {
        continue;
    }

    $pluginFiles = glob($pluginDirectory . '/*.php');
    if ($pluginFiles === false) {
        continue;
    }

    sort($pluginFiles, SORT_STRING);
    foreach ($pluginFiles as $pluginFile) {
        include_once $pluginFile;
    }
}

require_once '/usr/share/php/Composer/InstalledVersions.php';

(function (): void {
    $versions = [];
    foreach (\Composer\InstalledVersions::getAllRawData() as $d) {
        $versions = array_merge($versions, $d['versions'] ?? []);
    }
    $name    = 'unknown';
    $version = '0.0.0';
    $versions[$name] = ['pretty_version' => $version, 'version' => $version,
        'reference' => null, 'type' => 'library', 'install_path' => __DIR__,
        'aliases' => [], 'dev_requirement' => false];
    \Composer\InstalledVersions::reload([
        'root' => ['name' => $name, 'pretty_version' => $version, 'version' => $version,
            'reference' => null, 'type' => 'project', 'install_path' => __DIR__,
            'aliases' => [], 'dev' => false],
        'versions' => $versions,
    ]);
})();
