<?php
/**
 * Debian autoloader for php-vitexsoftware-multiflexi-core
 * Generated by phpab during package build
 */

// Load dependency autoloaders
require_once '/usr/share/php/Ease/autoload.php';
require_once '/usr/share/php/EaseFluentPDO/autoload.php';
require_once '/usr/share/php/JsonSchema/autoload.php';

// PSR-4 autoloader for MultiFlexi classes
spl_autoload_register(function (string $class): void {
    $prefixes = [
        'MultiFlexi\\' => '/usr/share/php/MultiFlexi/',
    ];
    foreach ($prefixes as $prefix => $baseDir) {
        $len = strlen($prefix);
        if (strncmp($prefix, $class, $len) !== 0) {
            continue;
        }
        $relativeClass = substr($class, $len);
        $file = $baseDir . str_replace('\\', '/', $relativeClass) . '.php';
        if (file_exists($file)) {
            require $file;
            return;
        }
    }
});
